### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [TheEdgeOfRage/boban-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by TheEdgeOfRage** [comment]
lol, I just migrated this from another git server to here to have a copy for myself, never thought people would actually find it :sweat_smile: I will add a full readme with screenshots of all the different prompt segments tomorrow :)

**Comment by unixorn** [comment]
Cool, thanks. Either add a PR on [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins/) when you're ready, or just close this if you'd prefer I add it. If there's any particular phrasing you want me to use in the entry, add it here.

**Comment by TheEdgeOfRage** [comment]
@unixorn I have added a basic readme with a screenshot. I want to expand more on it at some point and list more detailed explanations for all the prompt segments, but this will do for now :)

Feel free to add it to your list
